FROM node:lts-alpine

WORKDIR /app



# Set build-time environment variables
ARG MONGO_CONNECTION_STRING
ARG PORT
ARG DATABASE_URL
ARG STRIPE_SECRET_KEY
ARG APP_SECRET
ARG STRIPE_WEBHOOK_SECRET
ARG SUPPORT_EMAIL
ARG DEV_POSTMARKAPI_KEY
ARG PROD_POSTMARKAPI_KEY
ARG APP_ENV
ARG DEV_URL
ARG APP_URL
ARG TEST_HOST_UID
ARG TEST_CUSTOMER_UID
ARG TEST_ADMIN_UID
ARG EXPO_ACCESS_TOKEN
ARG DEV_EXPO_ACCESS_TOKEN
ARG DEV_MOBILE_APP_SCHEME
ARG MOBILE_APP_SCHEME
ARG TEST_PUSH_TOKEN
ARG DEV_CONTROL_PANEL_URL
ARG CONTROL_PANEL_URL
ARG MTN_COLLECTION_USER_ID
ARG MTN_DISBURSEMENT_USER_ID
ARG MTN_COLLECTION_API_KEY
ARG MTN_DISBURSEMENT_API_KEY
ARG MTN_TEST_URL
ARG MTN_PROD_URL
ARG MTN_COLLECTION_SUBSCRIPTION_KEY
ARG MTN_DISBURSEMENT_SUBSCRIPTION_KEY
ARG MTN_ENVIRONMENT
ARG SENTRY_DSN
ARG SENTRY_ENV
ARG MPESA_CALLBACK_URL
ARG MTN_CALLBACK_URL

ARG C2B_MPESA_CONSUMER_KEY
ARG C2B_MPESA_CONSUMER_SECRET
ARG C2B_MPESA_SHORT_CODE
ARG C2B_MPESA_PASS_KEY
ARG B2C_MPESA_CONSUMER_KEY
ARG B2C_MPESA_CONSUMER_SECRET
ARG B2C_MPESA_SHORT_CODE
ARG B2C_MPESA_PASS_KEY
ARG B2C_MPESA_PASSWORD
ARG B2C_MPESA_BUSINESS_NAME
ARG C2B_MPESA_BUSINESS_NAME
ARG MPESA_TEST_NUMBER

# Set runtime environment variables
ENV MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING
ENV PORT=${PORT}
ENV DATABASE_URL=${DATABASE_URL}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV APP_SECRET=${APP_SECRET}
ENV STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
ENV SUPPORT_EMAIL=${SUPPORT_EMAIL}
ENV DEV_POSTMARKAPI_KEY=${DEV_POSTMARKAPI_KEY}
ENV PROD_POSTMARKAPI_KEY=${PROD_POSTMARKAPI_KEY}
ENV APP_ENV=${APP_ENV}
ENV DEV_URL=${DEV_URL}
ENV APP_URL=${APP_URL}
ENV TEST_HOST_UID=${TEST_HOST_UID}
ENV TEST_CUSTOMER_UID=${TEST_CUSTOMER_UID}
ENV TEST_ADMIN_UID=${TEST_ADMIN_UID}
ENV EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
ENV DEV_EXPO_ACCESS_TOKEN=${DEV_EXPO_ACCESS_TOKEN}
ENV DEV_MOBILE_APP_SCHEME=${DEV_MOBILE_APP_SCHEME}
ENV MOBILE_APP_SCHEME=${MOBILE_APP_SCHEME}
ENV TEST_PUSH_TOKEN=${TEST_PUSH_TOKEN}
ENV DEV_CONTROL_PANEL_URL=${DEV_CONTROL_PANEL_URL}
ENV CONTROL_PANEL_URL=${CONTROL_PANEL_URL}
ENV MTN_COLLECTION_USER_ID=${MTN_COLLECTION_USER_ID}
ENV MTN_DISBURSEMENT_USER_ID=${MTN_DISBURSEMENT_USER_ID}
ENV MTN_COLLECTION_API_KEY=${MTN_COLLECTION_API_KEY}
ENV MTN_DISBURSEMENT_API_KEY=${MTN_DISBURSEMENT_API_KEY}
ENV MTN_TEST_URL=${MTN_TEST_URL}
ENV MTN_PROD_URL=${MTN_PROD_URL}
ENV MTN_COLLECTION_SUBSCRIPTION_KEY=${MTN_COLLECTION_SUBSCRIPTION_KEY}
ENV MTN_DISBURSEMENT_SUBSCRIPTION_KEY=${MTN_DISBURSEMENT_SUBSCRIPTION_KEY}
ENV MTN_ENVIRONMENT=${MTN_ENVIRONMENT}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_ENV=${SENTRY_ENV}
ENV MPESA_CALLBACK_URL=${MPESA_CALLBACK_URL}
ENV MTN_CALLBACK_URL=${MTN_CALLBACK_URL}

ENV C2B_MPESA_CONSUMER_KEY=$C2B_MPESA_CONSUMER_KEY
ENV C2B_MPESA_CONSUMER_SECRET=$C2B_MPESA_CONSUMER_SECRET
ENV C2B_MPESA_SHORT_CODE=$C2B_MPESA_SHORT_CODE
ENV C2B_MPESA_PASS_KEY=$C2B_MPESA_PASS_KEY
ENV B2C_MPESA_CONSUMER_KEY=$B2C_MPESA_CONSUMER_KEY
ENV B2C_MPESA_CONSUMER_SECRET=$B2C_MPESA_CONSUMER_SECRET
ENV B2C_MPESA_SHORT_CODE=$B2C_MPESA_SHORT_CODE
ENV B2C_MPESA_PASS_KEY=$B2C_MPESA_PASS_KEY
ENV B2C_MPESA_PASSWORD=$B2C_MPESA_PASSWORD
ENV B2C_MPESA_BUSINESS_NAME=$B2C_MPESA_BUSINESS_NAME
ENV C2B_MPESA_BUSINESS_NAME=$C2B_MPESA_BUSINESS_NAME
ENV MPESA_TEST_NUMBER=$MPESA_TEST_NUMBER


COPY . .


RUN yarn

RUN npx prisma generate

RUN npx prisma migrate deploy

CMD ["yarn", "start"]
